### ISSUE TITLE
Device Support Files for watchOS 6.2

### ISSUE THREAD

**Issue by acceleroto** [iGhibli/watchOS-DeviceSupport#2]
Can you please add the device support files for watchOS 6.2? Thanks!

**Comment by iGhibli** [comment]
@acceleroto The latest version [watchOS 6.2](https://github.com/iGhibli/watchOS-DeviceSupport/commit/d376adf4561c03d70ba2feae30a7c5bd6add026c) support files is already uploaded. Hope it's helpful to you.

**Comment by acceleroto** [comment]
Perfect, thanks for adding them!
